version: 2
jobs:
  build:
    working_directory: ~/sample-circleci
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/openjdk:8
    steps:
      - run: gradle build
            path: ~/sample-circleci
      - store_artifacts:
            path: ~/sample-circleci/build/libs/sample-circleci.jar

  test:
    working_directory: ~/sample-circleci
    docker:
      - image: circleci/openjdk:8
    steps:
      - run: |
          mkdir -p junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit          
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
