machine:
  timezone:
    America/Los_Angeles
  java:
    version: openjdk8

test:
  pre:
    - gradle javadoc
  override:
    - gradle check
  post:
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/test-results/*/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

general:
  artifacts:
    - "build/reports/"
    - "build/docs/"
